services:
  apache:
    container_name: contapa2-m1-WS
    cap_add:
      - NET_BIND_SERVICE
    build:
      context: ./apache
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8085:80"     # HTTP
    environment:
      DB_HOST: contsql-m1-WS
      DB_NAME: milestone
      DB_USER: appuser
      DB_PASSWORD: apppass
    volumes:
      - ./web:/var/www/html
    healthcheck:
      # Check PHP + Apache + DB connectivity via a lightweight endpoint
      test: ["CMD", "curl", "-fsS", "http://localhost"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 20s

  db:
    container_name: contsql-m1-WS
    image: mariadb:11.4
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: milestone
      MARIADB_USER: appuser
      MARIADB_PASSWORD: apppass
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      # MariaDB official images provide healthcheck.sh
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5